spring:
  threads:
    virtual:
      enabled: true
  datasource:
    global:
      jdbc-url: jdbc:mysql://localhost:3306/wallet_global
      username: root
      password: Admin@123
    shard0:
      jdbc-url: jdbc:mysql://localhost:3306/wallet_shard_0
      username: root
      password: Admin@123
    shard1:
      jdbc-url: jdbc:mysql://localhost:3306/wallet_shard_1
      username: root
      password: Admin@123
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
